/**
 * settings.js
 *
 * Settings panel logic — fully decoupled from HTML inline scripts
 * (per the documented Phase 0 refactor: "Extract all inline HTML script
 * logic into settings.js"). Populates the panel from CONFIG, wires
 * open/close/save controls, and persists user-editable values back into
 * the session (not into config.js itself — that file is generated by
 * the CI secret-injection step and is read-only at runtime).
 *
 * ── ⚠ RECONSTRUCTION NOTICE ──────────────────────────────────────────
 *
 * This file was reconstructed from project documentation, not extracted
 * from your actual source. The handover transcript documents that
 * settings.js exists, that it reads CONFIG near its own line 19 (visible
 * in a captured stack trace), and that it contains "all settings panel
 * logic, fully decoupled from HTML" — but no literal source was included
 * in the upload. Replace this file with your real settings.js if it
 * differs from this baseline.
 *
 * Observed stack trace from handover (informed the structure below):
 *   "settings.js:19 Uncaught ReferenceError: CONFIG is not defined
 *      at HTMLDocument.<anonymous> (settings.js:19:29)"
 *   → confirms settings.js reads CONFIG inside a DOMContentLoaded handler,
 *     and that script load order (config.js before settings.js) is load-
 *     bearing — breaking it throws exactly this error.
 *
 * ── Dependencies ──────────────────────────────────────────────────────
 *   config.js   — must load first; provides window.CONFIG
 *   utils.js    — must load before this file; provides setInfoValue,
 *                 toggleSettingsPanel, log
 *
 * ── Script load order (per handover) ────────────────────────────────
 *   config.js → utils.js → [module files] → signaling.js → app.js →
 *   debug.js → diagnostics.js → sender.js/viewer.js → settings.js
 */

/* global CONFIG, setInfoValue, toggleSettingsPanel, log */

document.addEventListener('DOMContentLoaded', () => {

  // ── Populate read-only CONFIG fields into the panel ─────────────────────
  //
  // This is the exact call site that produced the documented
  // "CONFIG is not defined" error when config.js failed to load before
  // this file (either due to script tag ordering or a parse error in
  // config.js from an unreplaced %%PLACEHOLDER%%).
  if (typeof CONFIG === 'undefined') {
    log('settings.js: CONFIG is not defined — check script load order ' +
        'and that config.js has no unreplaced %%PLACEHOLDER%% tokens.', 'error');
    return;
  }

  setInfoValue('settings-session-id',     CONFIG.SESSION_ID     ?? '—');
  setInfoValue('settings-signaling-url',  CONFIG.SIGNALING_URL  ?? '—');
  setInfoValue(
    'settings-turn-status',
    Array.isArray(CONFIG.TURN_SERVERS) && CONFIG.TURN_SERVERS.length > 0
      ? `${CONFIG.TURN_SERVERS.length} server(s) configured`
      : 'No TURN servers configured'
  );

  // ── Wire panel open/close controls ──────────────────────────────────────

  const openBtn  = document.getElementById('settings-open-btn');
  const closeBtn = document.getElementById('settings-close-btn');

  openBtn?.addEventListener('click', () => toggleSettingsPanel(true));
  closeBtn?.addEventListener('click', () => toggleSettingsPanel(false));

  // Close on backdrop click (if a backdrop element is present)
  document.getElementById('settings-backdrop')
    ?.addEventListener('click', () => toggleSettingsPanel(false));

  // Close on Escape key
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape') toggleSettingsPanel(false);
  });

  // ── Session-only editable preferences ───────────────────────────────────
  //
  // These are NOT written back to config.js (which is generated at deploy
  // time by CI and is read-only). They're session-local UI preferences —
  // e.g. toggling the GPS/compass overlay, debug panel visibility, marker
  // detection highlight color. Stored in memory only; reset on reload.
  //
  // NOTE: per project constraints, browser localStorage/sessionStorage
  // should not be relied on for persistence across reloads in any
  // artifact context — if you want these to persist, wire them to your
  // own backend or a project-level storage mechanism instead.

  const sessionPrefs = {
    showDebugPanel:    false,
    showGPSOverlay:    true,
    showMarkerOverlay: true,
  };

  const debugToggle  = document.getElementById('settings-toggle-debug');
  const gpsToggle    = document.getElementById('settings-toggle-gps');
  const markerToggle = document.getElementById('settings-toggle-markers');

  debugToggle?.addEventListener('change', e => {
    sessionPrefs.showDebugPanel = e.target.checked;
    const panel = document.getElementById('debug-log');
    if (panel) panel.hidden = !sessionPrefs.showDebugPanel;
    log(`Debug panel ${sessionPrefs.showDebugPanel ? 'shown' : 'hidden'}`);
  });

  gpsToggle?.addEventListener('change', e => {
    sessionPrefs.showGPSOverlay = e.target.checked;
    const overlay = document.getElementById('location-overlay');
    if (overlay) overlay.style.display = sessionPrefs.showGPSOverlay ? '' : 'none';
    log(`GPS overlay ${sessionPrefs.showGPSOverlay ? 'shown' : 'hidden'}`);
  });

  markerToggle?.addEventListener('change', e => {
    sessionPrefs.showMarkerOverlay = e.target.checked;
    log(`Marker overlay ${sessionPrefs.showMarkerOverlay ? 'shown' : 'hidden'}`);
    // markers.js consumers can read window.sessionPrefs.showMarkerOverlay
    // to decide whether to render detected marker outlines, if applicable.
  });

  // Expose for other modules to read without re-querying the DOM
  window.sessionPrefs = sessionPrefs;

  log('settings.js initialised');
});
